-- Databricks notebook source
CREATE OR REPLACE STREAMING LIVE TABLE SALES_DATA
COMMENT "SALES DATA BRONZ LAYER"
AS
SELECT * FROM CLOUD_FILES("/mnt/salesorderdetail","csv")


-- COMMAND ----------

CREATE OR REPLACE STREAMING LIVE TABLE PRODUCT_DATA
COMMENT "PRODUCT DATA BRONZ LAYER"
AS
SELECT * FROM CLOUD_FILES("/mnt/sourcedataforproduct","csv")

-- COMMAND ----------

CREATE OR REPLACE STREAMING LIVE TABLE SALES_DATA_CLEANED
(
CONSTRAINT SALES_NULL_REMOVE_DATA EXPECT (SalesOrderID IS NOT NULL ) ON VIOLATION DROP ROW
)
COMMENT "CLEANED SALES DATA"
AS
SELECT * FROM STREAM(LIVE.SALES_DATA) 

-- COMMAND ----------

CREATE OR REPLACE STREAMING LIVE TABLE SALES_DATA_TARGET;

APPLY CHANGES INTO LIVE.SALES_DATA_TARGET
FROM STREAM(LIVE.SALES_DATA_CLEANED)
KEYS (SalesOrderID,SalesOrderDetailID)
SEQUENCE BY SalesOrderID




-- COMMAND ----------

CREATE OR REPLACE LIVE VIEW category_silver_DATA
AS
SELECT CATEGORY.NAME,SUM(SALES.LineTotal) AS AMOUNT 
FROM LIVE.SALES_DATA_TARGET AS SALES
INNER JOIN LIVE.PRODUCT_DATA AS CATEGORY
ON SALES.ProductID = CATEGORY.ProductID
GROUP BY CATEGORY.NAMEhive_metastore.default.category_bronz

