-- Databricks notebook source
CREATE OR REPLACE STREAMING LIVE TABLE CATEGORY_BRONZ
COMMENT "STRUCTURED STREAMING BRONZ TABLE FOR CATEGORY DATA"
AS
SELECT *,
current_timestamp() AS LOAD_TIMESTAMP,
input_file_name() AS INPUT_FILENAME
FROM cloud_files("${SourceFilePath}","csv")

-- COMMAND ----------


CREATE OR REPLACE STREAMING LIVE TABLE CATEGORY_SILVER
(
CONSTRAINT PRODUCT_WEIGHT EXPECT (cast(Weight as decimal(10,4)) IS NOT NULL) ON VIOLATION DROP ROW
)
COMMENT "SILVER TABLE FOR CATEGORY DATA"
AS
SELECT * EXCEPT(LOAD_TIMESTAMP,INPUT_FILENAME)
FROM STREAM(LIVE.CATEGORY_BRONZ)




-- COMMAND ----------

CREATE OR REPLACE LIVE TABLE CATEGORY_GOLD
COMMENT "GOLD TABLE FOR CATEGORY DATA"
AS
SELECT Color, SUM(ListPrice) AS Amount FROM LIVE.CATEGORY_SILVER
GROUP BY Color
